# Generated by Django 4.2.6 on 2024-10-18 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfigurationPairings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_config_id", models.IntegerField()),
                ("device_config_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DeviceConfigurationParameterName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("range", models.JSONField()),
                ("quantum", models.FloatField()),
                ("default_value", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="DeviceMeasure",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("config_id", models.IntegerField(blank=True, default=None, null=True)),
                ("version", models.IntegerField()),
                ("config", models.JSONField()),
                ("pta", models.JSONField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("points_count", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorConfigurationParameterName",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DoctorConfigurationParameterValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfigurationparametername",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_id", models.IntegerField()),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfigurationparametername",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.doctorconfigurationparametervalue",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceMeasurePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("battery", models.FloatField()),
                ("integrity", models.FloatField()),
                ("sp02", models.FloatField()),
                ("bpm", models.FloatField()),
                ("obda", models.FloatField()),
                ("audio_sp1", models.FloatField()),
                ("audio_sp2", models.FloatField()),
                ("audio_sp3", models.FloatField()),
                ("audio_sp4", models.FloatField()),
                ("audio_sp5", models.FloatField()),
                ("audio_sp6", models.FloatField()),
                ("audio_sp7", models.FloatField()),
                ("audio_sp8", models.FloatField()),
                ("audio_sp9", models.FloatField()),
                ("audio_sp10", models.FloatField()),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.devicemeasure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceConfigurationParameterValue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=255)),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfigurationparametername",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeviceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("config_id", models.IntegerField()),
                (
                    "param",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfigurationparametername",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client.deviceconfigurationparametervalue",
                    ),
                ),
            ],
        ),
    ]
