# Generated by Django 4.2.6 on 2024-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deviceconfigurationparametername",
            name="unit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
