# Generated by Django 4.2.6 on 2024-11-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_deviceconfigurationparametername_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicemeasure",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
